### ISSUE TITLE
我是做html的不怎么懂ios 想吧论坛封装成iOS 看到你的源码 请问能否绑定URL

### ISSUE THREAD

**Issue by nongshifu** [LoongerTao/TLAnimationTabBar#1]
就是下面的5个导航栏 点击就打开指定url页面 怎么改

**Comment by LoongerTao** [comment]
绑定5个UIWebView 然后在UIWebView中打开你需要的url即可， 主要是存粹的html不好上AppStore哦，如果使用企业级开发账号发布还是可以的（不上AppStore）
